[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "employee-performance"
version = "1.0.0"
description = "Анализ эффективности работы разработчиков"
requires-python = ">=3.8"
dependencies = [
    "tabulate>=0.9.0",
]
